kind: Deployment
apiVersion: apps/v1
metadata:
  name: Dravid-Developer
spec:
  replicas: 2
  selector: # tells the controller which pods to watch/belong to
    matchLabels:
      app: Dravid-Developer
  template:
    metadata:
      labels:
        app: Dravid-Developer
    spec:
      containers:
        - name: Dravid-Developer
          image: amal98/pipeline-demo
          imagePullPolicy: Always
          ports:
            - containerPort: 80
