kind: Service
apiVersion: v1
metadata:
  name: Dravid-Developer
  labels:
    app: Dravid-Developer
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200
  selector:
    app: Dravid-Developer
  type: LoadBalancer
